### ISSUE TITLE
Training: how much GPU memory do you need/ 

### ISSUE THREAD

**Issue by foolhard** [polarisZhao/PFLD-pytorch#10]
I try to train on NV2080 (8G), but failed with out of memory. 
What's your training environment? What GPU do you use? 

RuntimeError: CUDA out of memory. Tried to allocate 26.00 MiB (GPU 0; 7.76 GiB total capacity; 6.88 GiB already allocated; 7.56 MiB free; 34.09 MiB cached)

**Comment by polarisZhao** [comment]
cuda 10.0
cudnn 7.5.0
GPU: RTX  2080ti
