### ISSUE TITLE
cuda版本过低问题，训练需要多少显存

### ISSUE THREAD

**Issue by ideask** [polarisZhao/PFLD-pytorch#11]
请问cuda版本需要到多少？目前我是cuda9.0，用gtx1060 6G训练模型，所需的显存足够吗？

**Comment by polarisZhao** [comment]
我用的版本是 cuda 10.0 + cudnn 7.5.0
显卡用的 rtx  2080ti。用 gtx 1060 6G 可能显存不够。

**Comment by ideask** [comment]
我将train batchsize换成128，占4G多显存，勉强跑一下，虽然慢一点。先看看效果怎样
