### ISSUE TITLE
提升精度问题

### ISSUE THREAD

**Issue by luckynote** [polarisZhao/PFLD-pytorch#17]
请问PFLD-pytorch目前可以复现论文中给出的精度吗？在WFLW上能够达到什么精度和速度？

**Comment by gjd2017** [comment]
我试了下，精度和速度都很困难达到论文中的。我也测了原作者开源的移动版的demo，效果也不是很理想哦。

**Comment by YUHANGZHANG7** [comment]
> 我试了下，精度和速度都很困难达到论文中的。我也测了原作者开源的移动版的demo，效果也不是很理想哦。

Hi, can you provide the relative code about processing 300W dataset?

**Comment by github-luffy** [comment]
> > 我试了下，精度和速度都很困难达到论文中的。我也测了原作者开源的移动版的demo，效果也不是很理想哦。
> 
> Hi, can you provide the relative code about processing 300W dataset?

You can try [PFLD_68points_Pytorch](https://github.com/github-luffy/PFLD_68points_Pytorch)
