### ISSUE TITLE
run train.py failed

### ISSUE THREAD

**Issue by ycdhqzhiai** [polarisZhao/PFLD-pytorch#18]
@polarisZhao 非常感谢您分享的代码，在运行训练脚本的时候loss部分报错了，这个怎么解决呢？
![image](https://user-images.githubusercontent.com/12273405/71151448-ac426200-226e-11ea-9f5c-503db6e2c7b7.png)

**Comment by Daonancai** [comment]
我也遇到这个问题了，请问是怎么解决的呢
