### ISSUE TITLE
模型训练时输入是BGR，使用camera时输入是RGB？

### ISSUE THREAD

**Issue by JinBuLanG** [polarisZhao/PFLD-pytorch#20]
训练时读入图片使用opencv，所以训练使用bgr，这是否会对结果造成影响？（我觉得不会）

**Comment by gjd2017** [comment]
模型是BRG ，camera.py 中的将“input = cv2.cvtColor(input, cv2.COLOR_BGR2RGB)”注释掉，另外，这个版本的确实效果不太好，不过还是很感谢作者的开源代码。
