### ISSUE TITLE
core dump

### ISSUE THREAD

**Issue by guojilei** [polarisZhao/PFLD-pytorch#32]
thank you for your code ,when i download this code and try to run camera.py ,some error happend, first ,my torch version is 1.1.0, it say volatile was moved ,use torch.no_grad() instead,second ,Illegal instruction (core dumped),  do you have this question, how to fix it? thank you

**Comment by github-luffy** [comment]
You can try [PFLD_68points_Pytorch](https://github.com/github-luffy/PFLD_68points_Pytorch)

**Comment by guojilei** [comment]
thank you i will try
