### ISSUE TITLE
运行pytorch2onnx.py报错

### ISSUE THREAD

**Issue by DWCTOD** [polarisZhao/PFLD-pytorch#33]
您好，运行pytorch2onnx.py报错了，

错误输出一大段内容，最后是：
====> check onnx model...
段错误 (核心已转储)

不知是什么原因，求大佬help

**Comment by github-luffy** [comment]
我之前遇到过 但还是直接转ncnn，是可以用的；
你可以试试转ncnn 然后看有没有用

**Comment by github-luffy** [comment]
如果想训练68点的话 可以直接点击[PFLD_68points_Pytorch](https://github.com/github-luffy/PFLD_68points_Pytorch)

**Comment by DWCTOD** [comment]
> 如果想训练68点的话 可以直接点击[PFLD_68points_Pytorch](https://github.com/github-luffy/PFLD_68points_Pytorch)

好的，谢谢大佬，我试一哈
我尝试了一下pytorch2onnx.py，发现原来是pytorch 、onnx、onnxruntime和onnx-simplifier版本的问题
经过不断尝试发现，下面的组合是可以的
pytorch=1.12.0
 onnx=1.5.0
 onnxruntime=0.4.0
 onnx-simplifier=0.1.8
![image](https://user-images.githubusercontent.com/41478810/88897480-ea304b80-d27d-11ea-81c6-8c0cd68531a6.png)
