### ISSUE TITLE
bad quality

### ISSUE THREAD

**Issue by iperov** [polarisZhao/PFLD-pytorch#4]
![python_2019-09-18_22-29-03](https://user-images.githubusercontent.com/8076202/65175324-be401900-da63-11e9-93e5-bfcd6fcfd95c.jpg)

**Comment by iperov** [comment]
![python_2019-09-18_22-30-04](https://user-images.githubusercontent.com/8076202/65175428-eaf43080-da63-11e9-8eea-012f31967658.jpg)

**Comment by iperov** [comment]
![python_2019-09-18_22-33-13](https://user-images.githubusercontent.com/8076202/65175667-59d18980-da64-11e9-8fa1-caa77ccbc710.jpg)

**Comment by iperov** [comment]
@polarisZhao 
can you please retrain your model with wider variations of scale/rotations/shift, 

also add channels shuffling
```
rnd_state = np.random.RandomState (sample_rnd_seed)
img = np.take (img_bgr, rnd_state.permutation(img_bgr.shape[-1]), axis=-1)
```

**Comment by polarisZhao** [comment]
Thanks for your advice, I will add more data augmentation to retain this model.

**Comment by polarisZhao** [comment]
U can use updeted checkpoint, the landmark will be better, Look forward to your feedback
