### ISSUE TITLE
实际测试效果很差，和论文出入较大，是因为提供的预训练模型还没充分收敛吗？

### ISSUE THREAD

**Issue by ZhengHui-Z** [polarisZhao/PFLD-pytorch#52]
实际测试效果很差，跟论文出入较大，不知道是不是训练不充分哦。

实验中使用了提供的预训练权重进行测试。

![face_landmark68](https://user-images.githubusercontent.com/13689856/115728917-8293d080-a3b7-11eb-98e5-4f1ae4964780.jpeg)

**Comment by zhyu95** [comment]
没使用预训练权重，训练不到100个epoch，loss就已经不下降了，现在训练到300个epoch，loss值基本没变化

**Comment by zyqdragon** [comment]
这是mtcnn检测人脸不准吧？
