### ISSUE TITLE
文件缺失的问题

### ISSUE THREAD

**Issue by wushunshun** [polarisZhao/PFLD-pytorch#6]
找不到‘./data/test_data/list.txt’文件

**Comment by polarisZhao** [comment]
执行完SetPreparation.py之后会生成这个文件

**Comment by wushunshun** [comment]
哦哦好的谢谢您~那请问pytorch能装CPU版本的跑您的程序嘛？我电脑GPU显卡算力不够



---原始邮件---
发件人: "zhaozhichao"<notifications@github.com&gt;
发送时间: 2019年9月24日(星期二) 晚上8:46
收件人: "polarisZhao/PFLD-pytorch"<PFLD-pytorch@noreply.github.com&gt;;
抄送: "wushunshun"<1048276743@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [polarisZhao/PFLD-pytorch] 文件缺失的问题 (#6)



执行完SetPreparation.py之后会生成这个文件

**Comment by polarisZhao** [comment]
cpu可以，需要稍微改改。CPU慢一些，我在macbookpro上试过。GPU相对快些

**Comment by wushunshun** [comment]
您好，请问在运行train.py这个文件的时候会不会在checkpoint文件夹下面的snapshot文件夹下面产生很多个checkpoint_epoch_x.pth.tar文件呀(x代表数字)啊，大概要产生多少个才会结束啊？实在是不知道最后运行出来是什么样子的，所以才来打扰您，辛苦您了，谢谢您



---原始邮件---
发件人: "zhaozhichao"<notifications@github.com&gt;
发送时间: 2019年9月27日(星期五) 上午8:44
收件人: "polarisZhao/PFLD-pytorch"<PFLD-pytorch@noreply.github.com&gt;;
抄送: "wushunshun"<1048276743@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [polarisZhao/PFLD-pytorch] 文件缺失的问题 (#6)



Closed #6.
