### ISSUE TITLE
训练模型

### ISSUE THREAD

**Issue by wushunshun** [polarisZhao/PFLD-pytorch#9]
不好意思，打扰了，请问运行train.py文件时，是不是会保存很多个check_point_epoch_x.pth.tar文件啊？会一直保存到多少个之后会停止train，或者说训练要大概要训练多久才结束呢？谢谢您！

**Comment by polarisZhao** [comment]
你可以通过tensorboard看相应的loss 的一些值， 然后通过观测曲线的值选择一个合适的， 代码中定义了1000个epoch， 但是大约二三百的时候就收敛了(具体数字我忘记了， 大致是这个数)。
